global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'client-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8080' ]
        labels:
          application: "client service"

  - job_name: 'server-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8081' ]
        labels:
          application: "server service"


